set_property IOSTANDARD LVCMOS33 [get_ports {a[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports blue]
set_property IOSTANDARD LVCMOS33 [get_ports green]
set_property IOSTANDARD LVCMOS33 [get_ports red]
set_property PACKAGE_PIN R16 [get_ports {a[1]}]
set_property PACKAGE_PIN T8 [get_ports {b[1]}]
set_property PACKAGE_PIN N15 [get_ports red]
set_property PACKAGE_PIN R12 [get_ports blue]
set_property PACKAGE_PIN M16 [get_ports green]

set_property PACKAGE_PIN T13 [get_ports {a[0]}]
set_property PACKAGE_PIN U8 [get_ports {b[0]}]
